### ISSUE TITLE
Add missing prebuilds for M1

### ISSUE THREAD

**Issue by lordnox** [julianhille/MuhammaraJS#100]

**Comment by tquid** [comment]
Seconded on this, pretty please! Tried the build script, and it failed.

**Comment by julianhille** [comment]
The build script should work as far as i know.
I'd love to provide such M1 prebuilds but i'am unable to, actually.
I don't have any M1 hardware and github actions does not provide 
a build environment so far. (waiting since 12/2020)
There seem to be licensing issues between github and apple according to this [thread](https://github.com/actions/virtual-environments/issues/2187)

**Comment by phillytan** [comment]
Bumping this issue -- there seems to be python-related issues when building on an Apple M1 CPU since macOS Monterey 12.3 removed the `python` CLI command ([check this site](https://scriptingosx.com/2022/03/macos-monterey-12-3-removes-python-2-link-collection/)).

**Comment by julianhille** [comment]
Should work with python 3. See musl builds in GitHub actions.
I need your help here in fixing it. I do not have an M1 and ga does not  have m1s either.

**Comment by phillytan** [comment]
I was able to get it working by running this command (assuming `python3` is installed via Brew. If not you can check `python3` location via `type python3`)

```bash
ln -s /opt/homebrew/bin/python3 /usr/local/bin/python
```

@julianhille Here are the node bindings compiled in my M1 Machine. I've compiled these bindings for Node 14 and 16. Feel free to attach this to the current release 🙂 Hope this helps!

[node-v83-darwin-arm64-unknown.tar.gz](https://github.com/julianhille/MuhammaraJS/files/8378897/node-v83-darwin-arm64-unknown.tar.gz)

[node-v93-darwin-arm64-unknown.tar.gz](https://github.com/julianhille/MuhammaraJS/files/8378859/node-v93-darwin-arm64-unknown.tar.gz)

**Comment by phillytan** [comment]
Hey @julianhille could we get an update on this issue? Many thanks!

**Comment by julianhille** [comment]
Github still has no machine with m1 silicon.
Currently considering options:
- build m1 on bitrise but this would break the nice gh actions release and test builds
- force arm builds on a mac os x86 11.x the build should work but testing would not work as it can not run the build binary
- having a look at apple dev cloud

**Comment by julianhille** [comment]
@phillytan would you checl this file:
https://github.com/julianhille/MuhammaraJS/suites/6187468619/artifacts/217663987

**Comment by julianhille** [comment]
Forgot: the file is prebuild for node 17.6.0

**Comment by julianhille** [comment]
@tquid you could also try that binary. I dont have a m1 and am so in the need of some support here.

**Comment by julianhille** [comment]
I got a friend to test it and he could confirm the file works on his m1. Will proceed and trying to create a release shortly

**Comment by marvinroger** [comment]
Is there anything I can help with in order to get this released? 😊

**Comment by julianhille** [comment]
Im currently on vacation and forgot about it. Will try to release tonight.
