### ISSUE TITLE
Some of the functions are commented in muhammara.d.ts file

### ISSUE THREAD

**Issue by martin-trajanovski** [julianhille/MuhammaraJS#107]
Not sure if this is going to be fixed soon but I see that some of the functions like `getObjectsContext`, `createPDFCopyingContextForModifiedFile` and others are commented inside `muhammara.d.ts` file. Would be good to include them and provide the types.

**Comment by julianhille** [comment]
Feel free to open a pr to fix that.
I have currently a lot ToDo. 😂

Cheers

**Comment by martin-trajanovski** [comment]
Will try to do it if I have some time. Thanks for the quick reply. 😃

**Comment by julianhille** [comment]
Hey there @martin-trajanovski would you mind taking a look at the "completed" typescript definitions? in https://github.com/julianhille/MuhammaraJS/pull/172

**Comment by julianhille** [comment]
@hypoterik you may also take a look at the pr
