### ISSUE TITLE
Error building on Macbook M1 / MacOS Monterey

### ISSUE THREAD

**Issue by vandamm** [julianhille/MuhammaraJS#138]
Trying to compile module on MacOS Monterey / Macbook Pro M1 Late 2021 raises following error:
```
../src/deps/PDFWriter/DecryptionHelper.cpp:372:7: error: no member named 'auto_ptr' in namespace 'std'
        std::auto_ptr<IByteReader> pDecryptStream(CreateDecryptionReader(new InputStringStream(inStringToDecrypt), mXcryptStrings->GetCurrentObjectKey(), mXcryptStrings->IsUsingAES()));
        ~~~~~^
```

This is because Mac OS now bundles C++17, which does not have `auto_ptr`. It must be replaced with either `unique_ptr` or `shared_ptr`

**Comment by julianhille** [comment]
I guess this should be tackled over there: https://github.com/galkahana/PDF-Writer/issues as this is only a copy that remote lib

**Comment by vandamm** [comment]
@julianhille  https://github.com/galkahana/PDF-Writer does not use auto_ptr in DecryptionHelper.cpp. Looks like your code uses an old version of PDF-Writer, maybe you can update it?

**Comment by julianhille** [comment]
Ahh. Did not update for a while. Will have a look.

**Comment by julianhille** [comment]
@vandamm please check out: https://github.com/julianhille/MuhammaraJS/pull/141 and see if this fixes it for you. Thanks

**Comment by vandamm** [comment]
@julianhille it builds without errors now. Waiting for a package update, thank you!

![Screenshot 2022-03-02 at 14 40 04](https://user-images.githubusercontent.com/576786/156355292-ea2a5974-5993-4c99-978e-f50a1b43cd34.png)

**Comment by julianhille** [comment]
Version 2.2.0 has been released which includes this fix.
