### ISSUE TITLE
Is there a multi-line support for text?

### ISSUE THREAD

**Issue by jaylee79** [julianhille/MuhammaraJS#153]
I couldn't find any information on it

**Comment by julianhille** [comment]
No there isn't. I once wrote a multi line multi page function in a private repository using this.

Maybe I could extract this and publish it.the nature of writing text onto a pdf does not really support that.

**Comment by julianhille** [comment]
Question: what do you mean with multi -line support? is it autobreak on "no space left" or do you want to see that "\n" gets auto wrapped?

**Comment by jaylee79** [comment]
Was originally thinking \n getting the new line.

**Comment by julianhille** [comment]
This should work using the Recipe class, which got added through merging hummus recipe into this package.

**Comment by julianhille** [comment]
You can add \n there OR use html to write your text.

I'm going to close this for now, but feel free to reopen if this still is an issue for you.
