### ISSUE TITLE
Is this package compatible with Node 14.x? If so, where can I find their binaries.

### ISSUE THREAD

**Issue by Amaanuddin** [julianhille/MuhammaraJS#154]

**Comment by julianhille** [comment]
Yes it is. You can just install it. the installation process downloads the binaries suited for env,Abi,platform automatically. The binaries itself are stored as GitHub release artifacts.

Hope that helps.

**Comment by Amaanuddin** [comment]
Can you specify which is the binary for Linux OS for node 14.x. I'm using windows OS and I need it for my lambda functions which are on Linux.

**Comment by julianhille** [comment]
Cant you use the node docker container from aws lambda and build in there? Copy the file out and be done? Not sure what libs lambda uses.

**Comment by julianhille** [comment]
Probably you need: https://github.com/julianhille/MuhammaraJS/releases/download/2.2.0/node-v83-linux-x64-glibc.tar.gz

**Comment by Amaanuddin** [comment]
> Probably you need: https://github.com/julianhille/MuhammaraJS/releases/download/2.2.0/node-v83-linux-x64-glibc.tar.gz

How to identify which node version is supported by the binary?

**Comment by julianhille** [comment]
V83 means Abi Version 83. Abi Version 83 should be node 14 only. There are several node-abi packages out there having a map of semver versions to Abi versions.

**Comment by vamshi9** [comment]
We are using serverless-lambda architecture to upload the built files. 

In our deployment pipeline, we have the following scripts where we replace windows `node_modules/muhammara-window`s with `node_modules/muhammara-linux`.
![image](https://user-images.githubusercontent.com/11611776/167283891-6314f078-24d4-4706-92ab-fcd27ca631af.png)


There can be better way as well, but the same trick worked with hummus using following binary with `10.x` node version
![image](https://user-images.githubusercontent.com/11611776/167283857-bc459393-28e4-4957-aa8b-c8308ca44fb7.png)


On using the above binary and deploy, I am facing this issue when I hit API
![image](https://user-images.githubusercontent.com/11611776/167283768-2a8f6014-ec46-4a7a-a741-370055caa169.png)

**Comment by julianhille** [comment]
Please supply commands as text so i can edit them to add some debug output

**Comment by julianhille** [comment]
Btw as far as i remember a normal linux is not the same as lambda aws linux.
So you may need to build that on your own. with a lambda node docker

Edit: fixed typo 'top' to 'to'

**Comment by vamshi9** [comment]
Can you please elaborate top build?

Also, I am attaching the above code as snippets
npm install

**Previous deployment script:**
```
# Replacing muhammara windows library with linux ones.
curl "https://github.com/julianhille/MuhammaraJS/releases/download/2.2.0/node-v83-linux-x64-glibc.tar.gz" | tar -xz
cp -f ./binding/muhammara.node ./node_modules/muhammara/binding/muhammara.node 
rm -r ./binding
```

**Previous Cloudwatch error log**
```
2022-05-08T05:45:50.976Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Error",
    "errorMessage": "/var/task/node_modules/muhammara/binding/muhammara.node: invalid ELF header",
    "code": "ERR_DLOPEN_FAILED",
    "stack": [
        "Error: /var/task/node_modules/muhammara/binding/muhammara.node: invalid ELF header",
        "    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Module.require (internal/modules/cjs/loader.js:974:19)",
        "    at require (internal/modules/cjs/helpers.js:101:18)",
        "    at Object.<anonymous> (/var/task/node_modules/muhammara/muhammara.js:5:34)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)"
    ]
}
```

However, I have understood that the way I need to read github zip should be different and I chaged the deployment script as follows:

**Updated deployment script:**
```
# Replacing muhammara windows library with linux ones.
curl -LO "https://github.com/julianhille/MuhammaraJS/releases/download/2.2.0/node-v83-linux-x64-glibc.tar.gz"
tar -xf node-v83-linux-x64-glibc.tar.gz
cp -f ./binding/muhammara.node ./node_modules/muhammara/binding/muhammara.node 
rm -r ./binding
```

But, now I am seeing a different error in cloudwatch

**New cloudwatch error:**
```
2022-05-09T17:17:37.129Z	4fd4de47-1c62-4241-84c1-d18062b12f7b	ERROR	Error: Failed to launch chrome!
/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/opt/nodejs/node_modules/puppeteer-core/lib/Launcher.js:348:14)
    at Interface.<anonymous> (/opt/nodejs/node_modules/puppeteer-core/lib/Launcher.js:337:50)
    at Interface.emit (events.js:412:35)
    at Interface.emit (domain.js:475:12)
    at Interface.close (readline.js:530:8)
    at Socket.onend (readline.js:254:10)
    at Socket.emit (events.js:412:35)
    at Socket.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

```

**Comment by julianhille** [comment]
@vamshi9 please test the binaries from this build: https://github.com/julianhille/MuhammaraJS/suites/6442574349/artifacts/235929295
They should be compatible with node 10, 12, 14 or 16 (depends on what you choose), amazons aws lambda linux and muhammara 2.2.0

The file contains several node versions pre build.

**Comment by julianhille** [comment]
Sorry but this new error has nothing to do with muhammara and i'm unable to help here as this is somehow a chrome on lambda issue as there are missing shared libs.
> But, now I am seeing a different error in cloudwatch
> 
> **New cloudwatch error:**
> 
> ```
> 2022-05-09T17:17:37.129Z	4fd4de47-1c62-4241-84c1-d18062b12f7b	ERROR	Error: Failed to launch chrome!
> /tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
> 
> 
> TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
> 
>     at onClose (/opt/nodejs/node_modules/puppeteer-core/lib/Launcher.js:348:14)
>     at Interface.<anonymous> (/opt/nodejs/node_modules/puppeteer-core/lib/Launcher.js:337:50)
>     at Interface.emit (events.js:412:35)
>     at Interface.emit (domain.js:475:12)
>     at Interface.close (readline.js:530:8)
>     at Socket.onend (readline.js:254:10)
>     at Socket.emit (events.js:412:35)
>     at Socket.emit (domain.js:475:12)
>     at endReadableNT (internal/streams/readable.js:1334:12)
>     at processTicksAndRejections (internal/process/task_queues.js:82:21)
> ```

**Comment by vamshi9** [comment]
I am continuing to see the launch chrome error even with the above binary mentioned. I will dig bit into the issue and update it here. Might help someone who faces similar issue!

> https://github.com/julianhille/MuhammaraJS/suites/6442574349/artifacts/235929295

**Comment by julianhille** [comment]
id consider this 'fixed'. Feel free to add infos to get chrome working on lambda.
