### ISSUE TITLE
Urgent HELP: yarn add muhammara fails to install package

### ISSUE THREAD

**Issue by MitchellTurk** [julianhille/MuhammaraJS#160]
Hi,

I am working on replacing hummus-recipe with muhammara and am unsuccessful in installing the package each time I try. I've been struggling to get these packages to work, and it has halted my productivity for the week. It works for my coworker, but fails on my machine. 

I did a full wipe of my Mac yesterday and reinstalled Monterey OS, as well as set up my development environment from scratch. I use homebrew and yarn. 

Any help you can offer would be greatly appreciated. 

When I run "yarn add muhammara", I receive the follow error message after about 30-45seconds (edited to be more concise):

error /Users/.../node_modules/muhammara: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build ${EXTRA_NODE_PRE_GYP_FLAGS:-""}
Arguments: 
Directory: /Users/.../node_modules/muhammara
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.9
node-pre-gyp info using node@18.1.0 | darwin | x64
node-pre-gyp info check checked for "/Users/.../node_modules/muhammara/binding/muhammara.node" (not found)
node-pre-gyp http GET https://github.com/julianhille/MuhammaraJS/releases/download/2.3.0/node-v108-darwin-x64-unknown.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/julianhille/MuhammaraJS/releases/download/2.3.0/node-v108-darwin-x64-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for muhammara@2.3.0 and node@18.1.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/julianhille/MuhammaraJS/releases/download/2.3.0/node-v108-darwin-x64-unknown.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@18.1.0 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@18.1.0 | darwin | x64
gyp info find Python using Python version 3.8.9 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
(node:35909) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/.../node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/.../node_modules/muhammara/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/.../node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/.../Library/Caches/node-gyp/18.1.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/.../Library/Caches/node-gyp/18.1.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/.../node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/.../Library/Caches/node-gyp/18.1.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/.../node_modules/muhammara',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@18.1.0 | darwin | x64
gyp info spawn make

{....lots of hidden info here, no problems...}

env: python: No such file or directory
make: *** [Release/pdfwriter.a] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/.../node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/usr/local/Cellar/node/18.1.0/bin/node" "/Users/.../node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/.../node_modules/muhammara/binding/muhammara.node" "--module_name=muhammara" "--module_path=/Users/.../node_modules/muhammara/binding" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
gyp ERR! cwd /Users/.../node_modules/muhammara
gyp ERR! node -v v18.1.0
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/18.1.0/bin/node /Users/.../node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/.../node_modules/muhammara/binding/muhammara.node --module_name=muhammara --module_path=/Users/.../node_modules/muhammara/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/.../node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Darwin 21.5.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/18.1.0/bin/node" "/Users/.../node_modules/muhammara/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" ""
node-pre-gyp ERR! cwd /Users/.../node_modules/muhammara
node-pre-gyp ERR! node -v v18.1.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.9
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/18.1.0/bin/node /Users/.../node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/.../node_modules/muhammara/binding/muhammara.node --module_name=muhammara --module_path=/Users/.../node_modules/muhammara

Please help as soon as possible, I urgently need to resume development work. 
Thank you in advance

**Comment by julianhille** [comment]
First of all you are using node 18.1 which is, till now, neither tested nor added prebuilts.

Then you seem to miss the python interpreter.

Please check if you can run `python` and / or `python3` from the the command line.

Please read this:
- https://github.com/nodejs/node-gyp#on-macos
- https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md
- https://github.com/nodejs/node-gyp#configuring-python-dependency

While you read and test i could start adding node v18.1 as a prebuilt

**Comment by MitchellTurk** [comment]
Thank you for the quick response.

Checking for python in the cli returns:

```
> python -V
zsh: command not found: python
> python3 -V
Python 3.8.9
> which python
python not found
> which python3
/usr/bin/python3
```

I do have Command Line Tools installed (installed automatically with Homebrew).

Is there another python interpreter than needs to be installed or do I simply need to run `npm config set python /path/to/executable/python` and point to usr/bin/python3?

Sorry If I'm asking obvious questions, I'm relatively new to software development and want to get this right after doing a full wipe

**Comment by julianhille** [comment]
You could / should try that as this seems to be the easiest way.
 
> Is there another python interpreter than needs to be installed or do I simply need to run `npm config set python /path/to/executable/python` and point to usr/bin/python3?
> 


> Sorry If I'm asking obvious questions, I'm relatively new to software development and want to get this right after doing a full wipe

No problem. Everything is good.

**Comment by MitchellTurk** [comment]
After running the above command, I am still getting back:
```
> npm config set python /usr/bin/python3
> which python
python not found
> python -V
zsh: command not found: python
```

Also, is it necessary to downgrade my version of node temporarily?

**Comment by julianhille** [comment]
Getting the error is still fine, it does not alter any links or pyton interpreter settings of your system it just tells npm where python is located. So you need to `yarn add muhammara`


> After running the above command, I am still getting back:
> 
> ```
> > npm config set python /usr/bin/python3
> > which python
> python not found
> > python -V
> zsh: command not found: python
> ```
> 

It is not necessary, but it makes things easier. Switching node version to 17.x with `nvm` would allow to download prebuilts and so would not need to compile muhammara.
If you need 18.x i would not recommend in downgrading but keep trying to compile.

> Also, is it necessary to downgrade my version of node temporarily?

**Comment by MitchellTurk** [comment]
> It is not necessary, but it makes things easier. Switching node version to 17.x with `nvm` would allow to download prebuilts and so would not need to compile muhammara. If you need 18.x i would not recommend in downgrading but keep trying to compile.
> 

Understood. That makes much more sense, thank you for the explanation. 
Now that I set the npm config for python, I will try compiling again. If it fails, I will downgrade until the v18 prebuilts are available.

Thank you very much for helping me debug. I greatly appreciate your assistance.

**Comment by julianhille** [comment]
you could buy me a coffee at any time :>
https://github.com/sponsors/julianhille

**Comment by MitchellTurk** [comment]
Ended up downgrading to node 16 and everything worked great.
Thanks again for your help, there is certainly a coffee coming your way!

**Comment by cengit** [comment]
definitely node version compatible issue, just use node v14, or v16 to give it a try.

this works for  me
