### ISSUE TITLE
Password protection doesn't work using buffers

### ISSUE THREAD

**Issue by kami4ka** [julianhille/MuhammaraJS#182]
I tried to password-protect PDF from buffer:

```
        const sourceStream = new muhammara.PDFRStreamForBuffer(buffer);
        const targetStream = new muhammara.PDFWStreamForBuffer();
        const modPdfWriter = muhammara.createWriterToModify(sourceStream, targetStream, {
            version: muhammara.ePDFVersion17,
            userPassword: password,
            ownerPassword: password,
            userProtectionFlag: 4,
        });
        modPdfWriter.end();

        return targetStream.buffer;
```        
Still, the result buffer is not password protected and I can open and view PDF using macOS Preview

**Comment by julianhille** [comment]
as far as i understand the code after a quick lookup the passwords aren't there to ensure password protection to an unprotected file, they are there to set the password to modify an already encrypted file.

Which feels odd.

**Comment by julianhille** [comment]
i mean especially in `createWriterToModify` it seems to be intended.
I also can not change the password, when modifying it, of the source pdf. Neither with stream nor directly using files.

**Comment by kami4ka** [comment]
Yeah. My bad. I haven't found explicit documentation about this one, so I mistakenly thought that it sets the password.

I found that there is no way to encrypt files using a buffer - e.g. no `recrypt` function with Buffers support.

**Comment by julianhille** [comment]
You could try and throw the buffer into the `recrypt` function and then return the buffer.

**Comment by kami4ka** [comment]
There is no such option, at least at typings:

``` 
export function recrypt(
    originalPdfPath: FilePath,
    newPdfPath: FilePath,
    options?: PDFRecryptOptions,
  ): void;
  export function recrypt(
    originalPdfStream: PDFRStreamForFile,
    newPdfStream: PDFWStreamForFile,
    options?: PDFRecryptOptions,
  ): void;
  ```

**Comment by julianhille** [comment]
```	
describe('Encrypt PDF With a Password as stream from Buffer', function() {
		it('should complete without error', function() {
			var result = fs.readFileSync(__dirname +  '/TestMaterials/PDFWithPassword.PDF')
			var source = new muhammara.PDFRStreamForBuffer(result);
			var target = new muhammara.PDFWStreamForBuffer();
			muhammara.recrypt(
				source,
				target,
				{
					password:'user',
					userPassword: 'user1',
					ownerPassword: 'owner1',
					userProtectionFlag: 4
				});
			fs.writeFileSync(__dirname + '/output/RecryptPDFOriginalToPasswordProtectedBuffer2.PDF', target.buffer)
		});
	});
```

works any ways.

**Comment by julianhille** [comment]
Thank you very much for pointing that out. there you go, will be added.

https://github.com/julianhille/MuhammaraJS/issues/183

**Comment by kami4ka** [comment]
Thanks.
I initially started with [hummus-recipe](https://github.com/chunyenHuang/hummusRecipe), but it doesn't allow buffers as well by just sending a small undiscoverable message to the console, which wasted hours of my life 🙂

**Comment by julianhille** [comment]
Happy to help
