### ISSUE TITLE
Deployment issues to AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by chuckntaylor** [julianhille/MuhammaraJS#212]
I'm in the process of deploying a NodeJS application that I have pushed to AWS Elastic Beanstalk many times in the past. I was hoping someone might shed some light on why I might be having this problem.

When the server is started it fails with the following error:
```sh
node:internal/modules/cjs/loader:1189
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /var/app/current/node_modules/muhammara/binding/muhammara.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/app/current/node_modules/muhammara/muhammara.js:7:35)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

The error is saying that it cannot find
```
/var/app/current/node_modules/muhammara/binding/muhammara.node
```

However, when I ssh into the EC2 instance and navigate to that path I can see the file.
<img width="601" alt="Screen Shot 2022-10-19 at 9 58 05 PM" src="https://user-images.githubusercontent.com/17050325/196839229-403fb1e9-5a0b-4e65-8fa1-dedc1d7878b3.png">

I see it mentions `muhammara.js:7:35`

This is pointing to
```js
var muhammara = (module.exports = require(binding_path));
```

Which in turn is:
```js
var path = require("path");
var pregyp = require("@mapbox/node-pre-gyp");
var binding_path = pregyp.find(
  path.resolve(path.join(__dirname, "./package.json"))
);
```

I'm at a bit of a loss as to how to fix this.

Node version on the instance: v16.15.1
NPM version on the instance: 8.11.0

The problem may lie with pregyp, but wanted to check here first. Thank you kindly for your review.

**Comment by julianhille** [comment]
that looks very odd to me. 
Can you show what are the file rights and which user / group owns the binary `muhammara.node`. Please also check what user is running your node process.

I can only think of permission issues as all necessary files are there.

Are you using an special environment variable to tinker with how node finds modules?

**Comment by chuckntaylor** [comment]
Yes it is SUPER strange.
Thank you for providing your thoughts.
I'm no command line expert, but when I enter `ls -l` I see
```sh
-rwxr-xr-x 1 webapp webapp 4388824 Sep 30 12:03 muhammara.node
```

I am not exactly sure how to check what user is running the node process - especially as it crashes when I try to run it.
Permissions for the files in the app root is:
```sh
drwxr-xr-x   6 webapp webapp    271 Oct 20 05:16 .
drwxr-xr-x   3 root   root       21 Oct 20 05:16 ..
-rw-rw-r--   1 webapp webapp    740 Oct 19 23:56 buildspec.yml
drwxr-xr-x  13 webapp webapp    203 Oct 20 05:15 dist
drwxr-xr-x   3 root   root       17 Oct 20 05:15 dl.fedoraproject.org
-rw-rw-r--   1 webapp webapp    455 Oct 19 23:56 .gitignore
-rw-rw-r--   1 webapp webapp    432 Oct 19 23:56 .gitignore.dev
-rw-rw-r--   1 webapp webapp    485 Oct 19 23:56 .gitignore.prod
-rw-rw-r--   1 webapp webapp    313 Oct 19 23:56 jest.config.ts
drwxr-xr-x 526 webapp webapp  16384 Oct 20 05:15 node_modules
-rw-rw-r--   1 webapp webapp   2333 Oct 19 23:56 package.json
-rw-rw-r--   1 webapp webapp 693048 Oct 20 04:31 package-lock.json
drwxr-xr-x   3 webapp webapp     19 Oct 20 05:15 .platform
-rw-rw-r--   1 webapp webapp     18 Oct 19 23:56 Procfile
-rw-rw-r--   1 webapp webapp   6867 Oct 19 23:56 tsconfig.json
```

I have tried several other of your releases, but I keep getting the same error. Locally, I have no issues, so I'm certain it is not an issue with your project. I mostly came here because I am at a loss as to what the problem is, and thought you might have some insights.

**Comment by julianhille** [comment]
The error might also indicate that the linux machine you are on is missing some shared libs which muhammara needs. could you try to rebuild?

go into the muhammara root dir and: `npm rebuild`

**Comment by julianhille** [comment]
and please report result of: 

```
ldd /var/app/current/node_modules/muhammara/binding/muhammara.node

```

**Comment by chuckntaylor** [comment]
Thank you for your additional thoughts on the matter.
I ran `npm rebuild` inside `/var/app/current/node_modules/muhammara/`.
```sh
[root@ip-172-31-94-156 muhammara]# npm rebuild
rebuilt dependencies successfully
```

Then, I ran your command
```sh
[root@ip-172-31-94-156 current]# ldd /var/app/current/node_modules/muhammara/binding/muhammara.node
        not a dynamic executable
```

So I must be missing the libs?

**Comment by julianhille** [comment]
Sorry the order was bad, we should have done ldd before rebuilding. Can you restore the original file like how it is after an deployment?
I think its very odd that it states its not a dynamic lib, because it is.
When you restored the previous file:
- `cd /var/app/current/node_modules/muhammara/binding/`
- `md5sum muhammara.node`
- `ldd muhammara.node`

**Comment by julianhille** [comment]
and after that give it a go and try to compile it, `npm rebuild muhammara --build-from-source`

but beware you might need gcc, make and python3 to be able to compile it.

**Comment by chuckntaylor** [comment]
I am redeploying as I write this.
Just to clarify that last step. Am I executing `npm rebuild muhammara --build-from-source` from my app's root, or from `/var/app/current/node_modules/muhammara/`?

**Comment by julianhille** [comment]
sorry, that is a good question and i did not clarify. it is the apps root dir

**Comment by chuckntaylor** [comment]
Thanks. Just ran the first 3 commands so far
```sh
[root@ip-172-31-94-156 ~]# cd /var/app/current/node_modules/muhammara/binding/
[root@ip-172-31-94-156 binding]# md5sum muhammara.node
1023afc828c16a10ef35f3e97278a95c  muhammara.node
[root@ip-172-31-94-156 binding]# ldd muhammara.node
        not a dynamic executable
```
Shall I still continue with the rebuild command?

Again, thank you so much for providing your insight. I really appreciate your time.

**Comment by julianhille** [comment]
you could make a copy of the muhammara.node so that you can restore faster. but yes please continue

**Comment by julianhille** [comment]
i just downloaded the same file you got there and ran ldd on it and that just works here: 

```
>>> ldd muhammara.node 
	linux-vdso.so.1 (0x00007ffd3cbc8000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f1a02600000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f1a02922000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f1a02fdb000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1a02fd6000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f1a02200000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1a0300f000)
```

**Comment by julianhille** [comment]
ok wild idea: you are running on 32 bit linux?
what is the output of `uname -ar` ?

**Comment by chuckntaylor** [comment]
Haha I thought it was frozen there - I've never ran a `--build-from-source` command. Here is everything.
```sh
 _____ _           _   _      ____                       _        _ _
 | ____| | __   ___| |_(_) ___| __ )  ___  __ _ _ __  ___| |_ __ _| | | __
 |  _| | |/ _ \/ __| __| |/ __|  _ \ / _ \/ _\ | '_ \/ __| __/ _\ | | |/ /
 | |___| | (_| \__ \ |_| | (__| |_) |  __/ (_| | | | \__ \ || (_| | |   <
 |_____|_|\__,_|___/\__|_|\___|____/ \___|\__,_|_| |_|___/\__\__,_|_|_|\_\

 Amazon Linux 2 AMI

 This EC2 instance is managed by AWS Elastic Beanstalk. Changes made via SSH
 WILL BE LOST if the instance is replaced by auto-scaling. For more information
 on customizing your Elastic Beanstalk environment, see our documentation here:
 http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-ec2.html

[root@ip-172-31-94-156 ~]# cd /var/app/current/node_modules/muhammara/binding/
[root@ip-172-31-94-156 binding]# md5sum muhammara.node
1023afc828c16a10ef35f3e97278a95c  muhammara.node
[root@ip-172-31-94-156 binding]# ldd muhammara.node
        not a dynamic executable
[root@ip-172-31-94-156 binding]# cd /var/app/current
[root@ip-172-31-94-156 current]# ls
buildspec.yml  dist  dl.fedoraproject.org  jest.config.ts  node_modules  package.json  package-lock.json  Procfile  README.md  tsconfig.json
[root@ip-172-31-94-156 current]# cd /var/app/current/node_modules/muhammara/binding/
[root@ip-172-31-94-156 binding]# ls
muhammara.node
[root@ip-172-31-94-156 binding]# cp muhammara.node ./muhammara-backup.node
[root@ip-172-31-94-156 binding]# ls
muhammara-backup.node  muhammara.node
[root@ip-172-31-94-156 binding]# cd /var/app/current
[root@ip-172-31-94-156 current]# npm rebuild muhammara --build-from-source
rebuilt dependencies successfully
[root@ip-172-31-94-156 current]# 
```

**Comment by chuckntaylor** [comment]
```sh
[root@ip-172-31-94-156 current]# uname -ar
Linux ip-172-31-94-156.ec2.internal 4.14.281-212.502.amzn2.aarch64 #1 SMP Thu May 26 09:52:22 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by julianhille** [comment]
can you retest your app again, without redeploy or spawn a node repl and require muhammara.

You just compiled the complete lib again so it should be different now so also please try:

these commands again:
- `cd /var/app/current/node_modules/muhammara/binding/`
- `md5sum muhammara.node`
- `ldd muhammara.node`

**Comment by chuckntaylor** [comment]
Well that was a different result.
```sh
/var/app/current/node_modules/sharp/lib/sharp.js:34
  throw new Error(help.join('\n'));
  ^

Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-linux-arm64v8.node'
Require stack:
- /var/app/current/node_modules/sharp/lib/sharp.js
- /var/app/current/node_modules/sharp/lib/constructor.js
- /var/app/current/node_modules/sharp/lib/index.js
- /var/app/current/dist/api/pv-mini-apps-api/inforx/controllers/handlers/subscribeAccount.js
- /var/app/current/dist/api/pv-mini-apps-api/inforx/controllers/index.js
- /var/app/current/dist/api/pv-mini-apps-api/inforx/inforxRoutes.js
- /var/app/current/dist/api/pv-mini-apps-api/index.js
- /var/app/current/dist/api/index.js
- /var/app/current/dist/server.js
- /var/app/current/dist/index.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linux-arm64v8 runtime: "npm install --platform=linux --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/var/app/current/node_modules/sharp/lib/sharp.js:34:9)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/app/current/node_modules/sharp/lib/constructor.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
[root@ip-172-31-94-156 current]# 
```

And the results of the other commands
```sh
[root@ip-172-31-94-156 current]# cd /var/app/current/node_modules/muhammara/binding/
[root@ip-172-31-94-156 binding]# md5sum muhammara.node
bbfd13a2d022ea18479684fd53db4378  muhammara.node
[root@ip-172-31-94-156 binding]# ldd muhammara.node
        linux-vdso.so.1 (0x0000ffff9dacc000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x0000ffff9d533000)
        libm.so.6 => /lib64/libm.so.6 (0x0000ffff9d472000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000ffff9d441000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x0000ffff9d40c000)
        libc.so.6 => /lib64/libc.so.6 (0x0000ffff9d286000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffff9da8e000)
[root@ip-172-31-94-156 binding]# 
```

**Comment by julianhille** [comment]
ok. i guessed in the end so. You seem to try this:

- take some linux machine or maybe even windows (?)
- npm install there
- pack all the files
- send them somehow to ec2
- unpack
- make use of the unpacked

This does not work when you use / depend on binary modules like muhammara or sharp module.
You need to install the system on basically the same architecture.

This means npm install on the ec2 instance (remove node_modules dir beforehand)
or you could build this locally but then you need to do this in a docker container with the same setup like the ec2 instance.

**Comment by chuckntaylor** [comment]
One additional thought.
In my workflow, I am using AWS CodePipeline. So when I push a commit to my repo, it starts the build stage. At this stage, my understanding is that a container starts up, runs the commands in my `buildspec.yml`. From here, it packages/uploads the app, and then deploys it.

If I understand you correctly, it is important that the **building container architecture** needs to be basically the same as the EC2 instances? I just added `sharp` at the same time in the development of this app. I resize a logo image (using sharp) from S3, and add it to the header of an existing PDF (using your muhammara). So this is the first time encountering this error.

**Comment by julianhille** [comment]
what i see is: the install process installs a x86
_64  linux binary (muhammara) but in the end you are running on aarch64 which is arm v8 these are fundamentally different.

**Comment by chuckntaylor** [comment]
Okay. I am currently using [T4g instances ](https://aws.amazon.com/ec2/instance-types/t4/) which say they run on `Custom built AWS Graviton2 Processor with 64-bit Arm Neoverse cores`. I will change over to to a different one tomorow.

**Comment by chuckntaylor** [comment]
@julianhille You figured it out! I couldn't wait until tomorrow and I switched my dev server over (Had to build a new environment in AWS when switching architectures). Long story short, everything is working again, and no crashes. I'll move PROD on Monday and get some testing done, but you have been an enormous help.

**Comment by julianhille** [comment]
That's great to hear, glad you figured it out.
You could always buy me a coffee. 😬

Have a great day.
I'll close the ticket but feel free to reopen if necessary.

**Comment by chuckntaylor** [comment]
Thanks. You have a great day too. I don't know how Github notifies of these things, but absolutely a coffee was bought yesterday. 😀 Have a great weekend!

<img width="1024" alt="Screen Shot 2022-10-21 at 8 01 13 AM" src="https://user-images.githubusercontent.com/17050325/197191335-8715dd97-ef55-4a27-b660-7d11259486ee.png">

**Comment by julianhille** [comment]
im so sorry did not check my mails thoroughly enough. thanks!
