### ISSUE TITLE
merge muhammara-recipe and hummus recipe into this module

### ISSUE THREAD

**Issue by julianhille** [julianhille/MuhammaraJS#232]
The functionality these libraries add should be merged here as those seem a bit unmaintained.

**Comment by benbruscella** [comment]
This would be awesome, any timelines on this? 

Need a hand?

**Comment by julianhille** [comment]
I'd love to. Actually I'm pretty busy doing some private stuff, so give it a go.

What would be your plan where to add it?

**Comment by maximveksler** [comment]
Hey guys, i'm from the https://github.com/chunyenHuang/hummusRecipe/issues/240 discussion.

Happy to test and provide feedback.

**Comment by julianhille** [comment]
you may take a look here: https://github.com/julianhille/MuhammaraJS/pull/253 
only a draft for now.
