### ISSUE TITLE
Error implementing recrypt from absolute url file

### ISSUE THREAD

**Issue by hilmanski** [julianhille/MuhammaraJS#243]
Hi

I'm trying to use recrypt funciton to encrypt existing PDF file that I have as a link (not relative path)

```
const pdfUrlTest = "https://ABSOLUTE.URL/name.pdf"
    const inputStream = new muhammara.PDFRStreamForBuffer(pdfUrlTest);
    const outputStream = new muhammara.PDFWStreamForFile(`./public/tmp/des_${Date.now()}.pdf`);
    
    console.log('----------------')
    console.log('outputStream', outputStream)

    const passwordOptions = {
        password:'user',
        userPassword: 'user1',
        ownerPassword: 'owner1',
        userProtectionFlag: 4
    }

muhammara.recrypt(inputStream, outputStream, passwordOptions);
```

Error
 TypeError: Unable to recrypt files, check that input and output files are clear and arguments are coool

Question:
1. possible to inputstream from absolute Url? if not anyone know how?
2. I'm also planning to directly upload this file to cloud. Are there any way bypassing creating temporary localfile? directly as binary or some sort, then upload it?

Thanks

**Comment by hilmanski** [comment]
This also failed on my end with same error message
"TypeError: Unable to recrypt files, check that input and output files are clear and arguments are coool"

```
const inputStream = new muhammara.PDFRStreamForBuffer(pdfUrlTest);
const target = new muhammara.PDFWStreamForBuffer();
    muhammara.recrypt(
        inputStream,
        target,
        {
            password:'user',
            userPassword: 'user1',
            ownerPassword: 'owner1',
            userProtectionFlag: 4
        }
    );
```

**Comment by julianhille** [comment]
Hey there, i guess you misinterpret how PDFRStreamForBuffer works.

You need to put a "Buffer" into the constructor of `PDFRStreamForBuffer`, but actually you inject a string of a url and expect that it downloads the file.

What you could do is using a lib like `request` or `fetch` and make it return a buffer stream for you and inject that into the constructor of PDFRStreamForBuffer.

I'd close this for now, but feel free to reopen if you have any further infos or think i totally misunderstood. 

Thanks

**Comment by hilmanski** [comment]
thanks @julianhille will try it.
