### ISSUE TITLE
How to decrypt / remove password from PDF

### ISSUE THREAD

**Issue by hilmanski** [julianhille/MuhammaraJS#246]
Hi based on PDFHummus usage, I tried this to decrypt/remove password from PDF

```
 muhammara.recrypt(
                inputStream,
                target,
                {
                    password: previousPassword,
                }
            );
```

But it still returning the PDF with password protected
Anyone know how to remove password from a PDF by providing the previous password?

**Comment by julianhille** [comment]
Hey there,

that looks good so far and should work.
https://github.com/julianhille/MuhammaraJS/blob/develop/tests/Xcryption.js#L3 this is also a test which is running and still works (just checked it).

Are you able to provide a bit more code and sample files to dig a bit deeper?

**Comment by hilmanski** [comment]
Hi @julianhille 
here's my complete code

// Ignore the upload part.  
//I use similar method to successfully encrypt PDF, but now try to decrypt not working
```
   const { source, password } = req.body
    const target = new muhammara.PDFWStreamForBuffer()
    
    fetch(source).then(async (_res: any) => {
        if (_res.status !== 200) return

        const contentBuffer = await _res.buffer()
        const inputStream = new muhammara.PDFRStreamForBuffer(contentBuffer)

        try {
            muhammara.recrypt(inputStream, target, {
                password: password,
            })

            const uploadInfo = await uploadToCloud(target.buffer)

            if (uploadInfo.status == 'error') {
                console.log('Failed upload PDF ', uploadInfo)
                res.status(500).json({ error: uploadInfo.error })
            } else {
                res.status(200).json({ location: uploadInfo.message })
            }
        } catch (error) {
            console.log('Error recrypt password at encrypt ', error)
            res.status(500).json({ error: error })
        }
    })
```

Error message:
```
Error recrypt password at encrypt  TypeError: Unable to recrypt files, check that input and output files are clear and arguments are coool
```

Despite the error the PDF is still available on target.buffer but still protected.
So I'm still able to upload/download the PDF, but still protected.
I've tried put these values as password value: "user" | $correct-user-input-password | $wrong-user-input-password

**Comment by hilmanski** [comment]
Unrelated question, I saw in your test you provide hardcodes "user" as password's value. Is it because "user" the password for that PDF, or "user" is a constant here?

**Comment by julianhille** [comment]
> Hi @julianhille here's my complete code
> 
> // Ignore the upload part. //I use similar method to successfully encrypt PDF, but now try to decrypt not working
> 
> ```
>    const { source, password } = req.body
>     const target = new muhammara.PDFWStreamForBuffer()
>     
>     fetch(source).then(async (_res: any) => {
>         if (_res.status !== 200) return
> 
>         const contentBuffer = await _res.buffer()
>         const inputStream = new muhammara.PDFRStreamForBuffer(contentBuffer)
> 
>         try {
>             muhammara.recrypt(inputStream, target, {
>                 password: password,
>             })
> 
>             const uploadInfo = await uploadToCloud(target.buffer)
> 
>             if (uploadInfo.status == 'error') {
>                 console.log('Failed upload PDF ', uploadInfo)
>                 res.status(500).json({ error: uploadInfo.error })
>             } else {
>                 res.status(200).json({ location: uploadInfo.message })
>             }
>         } catch (error) {
>             console.log('Error recrypt password at encrypt ', error)
>             res.status(500).json({ error: error })
>         }
>     })
> ```
> 
> Error message:
> 
> ```
> Error recrypt password at encrypt  TypeError: Unable to recrypt files, check that input and output files are clear and arguments are coool
> ```
> 
> Despite the error the PDF is still available on target.buffer but still protected. So I'm still able to upload/download the PDF, but still protected. I've tried put these values as password value: "user" | $correct-user-input-password | $wrong-user-input-password

that error message also appears if the password is wrong. please check/ensure if the password is correct (by testing locally by hand and making sure the password is actually filled with what you expect it to be filled with.



i just tried this and it works flawless.

```
      const target = new muhammara.PDFWStreamForBuffer()
      var fileIn = fs.readFileSync(
        __dirname + "/TestMaterials/PDFWithPassword.PDF"
      );
      var source = new muhammara.PDFRStreamForBuffer(fileIn);
      muhammara.recrypt(
          source,
          target,
        {
          password: "user",
        }
      );

      fs.writeFileSync( __dirname + "/output/RecryptPDFToNoPw.PDF", target.buffer)

```

**Comment by julianhille** [comment]
> Unrelated question, I saw in your test you provide hardcodes "user" as password's value. Is it because "user" the password for that PDF, or "user" is a constant here?

user is the actual password

**Comment by hilmanski** [comment]
Thanks @julianhille for your patience and confirming it.
That's weird. If locally works, then the problem is when I'm using a remote url PDF? what's weird is I'm using the same flow to encrypt, and it worked successfully. for encrypt with Muhammara.

Will find another way and try it again..

**Comment by hilmanski** [comment]
Update.
I tried using the local encrypted file.
The problem I found is actually when exporting.
Using this
```
fs.writeFileSync( "./public/RecryptPDFToNoPw.PDF", target.buffer)
```
succesfully decrypt the PDF

but uploading it to cloud (in this case s3) return the PDF still protected

Here's the PDF I use (I encrypt this with Muhammara) https://pdfhost.io/v/jV.43gdgK_sample_locked with password "123"

**Comment by julianhille** [comment]
This is odd. The error clearly states that something with source, target or password is wrong / bad.
It does not make sense to me that writing locally works, but uploading it throws an error inside of muhammara.

The only thing i could think of is that `uploadToCloud` does something unexpected.
What happens if you:
- 'write it to disk and then open the file as buffer and upload it'
- 'transfer target.buffer into another buffer -> uploadToCloud'

**Comment by hilmanski** [comment]
Hi @julianhille it's something indeed wrong on my end. Really sorry for bothering you on this one.

**Comment by julianhille** [comment]
No problem. I hope you'll get it fixed soon.
