### ISSUE TITLE
Failed install with docker node 18-alpine

### ISSUE THREAD

**Issue by hilmanski** [julianhille/MuhammaraJS#248]
Hi.
Today I tried to install MuhammaraJS  on my docker machine which use
```
FROM node:18-alpine
```
But failed with this error messages

![Screen Shot 2022-12-12 at 17 25 23](https://user-images.githubusercontent.com/4522467/207009760-a7117cde-330e-4cd7-9a7a-dfd9d8f6e6cc.png)
![Screen Shot 2022-12-12 at 17 25 05](https://user-images.githubusercontent.com/4522467/207009781-f51a560c-7cab-4aef-aa84-569d210097e4.png)

Something to do with 'make'? 
I guess I need extra thing to install on my docker? 

thank!

**Comment by hilmanski** [comment]
Update
adding `RUN apk add g++ make py3-pip` this on my Dockerfile
```
...
COPY package.json ./

RUN apk add g++ make py3-pip

RUN yarn install
...
```

can solve the first error. Now the server is running but crashed after just adding require('muhammara')
![Screen Shot 2022-12-12 at 17 36 16](https://user-images.githubusercontent.com/4522467/207011795-8990ce7f-f7fb-43e9-8da8-1dec9f7482d5.png)

**Comment by julianhille** [comment]
ok you are using musl AND arm64 in the first build that is, why it needs to compile, cause i do not think i currently have pre compiled / builts binaries for this.

The second error might occur because then you run the code on a intel based instruction set or not on musl based lib (which is unlikely).

You need to get the cpu architecture and the lib (libc vs musl) straight, means you need to
use the same for the building and the running process.

on what are you running? If you would drop musl or arm64 (at least the combination of those) then you would also lose the need for compilation.

**Comment by hilmanski** [comment]
apologize I'm not familiar with things you mention above. 
Any actionable thing I need/can do to help me debug this and eventually get rid of the error?

Here's my complete docker file
```
FROM node:18-alpine
RUN apk add --no-cache libreoffice

WORKDIR /app

# Copy used fonts
COPY fonts ./
RUN mkdir -p /usr/share/fonts/truetype
RUN install -m644 ./*.ttf /usr/share/fonts/truetype/
RUN rm ./*.ttf

COPY package.json ./

RUN apk add g++ make py3-pip #<- newly added
 
RUN yarn install

RUN yarn global add pm2 -g

COPY . .
```

Not really sure what it means or what should I do here " If you would drop musl or arm64 (at least the combination of those) then you would also lose the need for compilation."

**Comment by julianhille** [comment]
what happens afterwards with the docker container or content of the container?
I'm sorry but this is not enough information to help you out.

**Comment by hilmanski** [comment]
When I'm running `docker-compose -f docker-compose.dev.yml up --build`
a. without `const muhammara = require('muhammara')` 
everything worked fine (with above docker setting)

b. with `const muhammara = require('muhammara')`
this error shows up, which make app crash and can't run the app
<img width="1066" alt="Screen Shot 2022-12-12 at 20 53 05" src="https://user-images.githubusercontent.com/4522467/207050100-daf38adf-4aea-4ced-b34f-1ea525b6da90.png">

LMK what other info should I provide.
Will continue search about this error

**Comment by julianhille** [comment]
`COPY . .` i got a feeling that this is the issue.

Please make sure that `node_modules` folder is not copied with this command, for testing purpose you might just delete or move `node_modules` dir on your host machine before building the alpine machine.

so run:
- `rm -R node_modules && docker-compose -f docker-compose.dev.yml up --build`

**Comment by julianhille** [comment]
another possible solution:

create a `.dockerignore` and put `**/node_modules` into it, that might also work.

**Comment by hilmanski** [comment]
thanks, I will explore this , seeing other similar problem https://github.com/kelektiv/node.bcrypt.js/issues/635 with similar approach. 

I'll close this for now since it doesn't looks like an issue specific for Muhammara, 
but will write my answer, once I solve it.

Thanks @julianhille for you guide and patience

**Comment by julianhille** [comment]
let me know if you need some further help

**Comment by hilmanski** [comment]
Thanks. haven't found a solution yet
I already add extra `**/node_modules on my dockerignore`
```
**/node_modules
node_modules
npm-debug.log
```

A.  When I remove my node_modules first, then running docker
It can't recognize my installed packages
for example: 
`pdf-services_1  | Error: Cannot find module 'cors'`

B. When I install my yarn locally first. 
Still the `dlopen` error and crash shows up.

will continue to explore

**Comment by hilmanski** [comment]
I got it running so far by adding volume on my docker-compose file

```
version: '3.8'

services:
  pdf-services:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8080:80
    volumes:
      - ./:/app
      - /app/node_modules <- this is newly added
    command:
      yarn dev
```

**Comment by julianhille** [comment]
that should not be needed as this resets the install on build time and moves the compile / install process to first run time. which gives a bad experience.

did you try removing node_modules from your disk before building the container or using the `.dockerignore` file? (there are more ways but these are the simplest)

**Comment by hilmanski** [comment]
thanks for giving more understanding.
Unfortunately that what worked for now.

Yes, I remove node_modules `rm -rf node_modules` and ignore it on .dockerignore  before building with these results:
https://github.com/julianhille/MuhammaraJS/issues/248#issuecomment-1347419738

**Comment by julianhille** [comment]
> thanks for giving more understanding. Unfortunately that what worked for now.
> 
> Yes, I remove node_modules `rm -rf node_modules` and ignore it on .dockerignore before building with these results: [#248 (comment)](https://github.com/julianhille/MuhammaraJS/issues/248#issuecomment-1347419738)

Ah sorry overlooked the comment. Let me reread the whole issue as that does not make sense to me, that's cors is missing then.

**Comment by julianhille** [comment]
Please try this and get back to me.
I changed a bit of the order and removed superfluous copy commands

```
FROM node:18-alpine
RUN apk add --no-cache libreoffice

WORKDIR /app

COPY . .
RUN rm -r node_modules/ # This should not be needed if .dockerignore includes node_modules


# Copy used fonts
# COPY fonts ./ # REMOVED as it seems to be included in COPY . .
RUN mkdir -p /usr/share/fonts/truetype
RUN install -m644 ./*.ttf /usr/share/fonts/truetype/
RUN rm ./*.ttf

# COPY package.json ./ # REMOVED as it seems to be included in COPY . .

RUN apk add g++ make py3-pip #<- newly added

RUN yarn install

RUN yarn global add pm2 -g

```

you then should be able to remove the newly added volume from docker-compose file

**Comment by hilmanski** [comment]
Hi @julianhille 
unfortunately same error happen after trying this order (dlopen error)
I tried even double "secure" everything by ignore node_modules on docker file and include rm command on dockerfile. Same result

IDK, maybe it's just something unique on my case. so don't worry.

Regardless of my problem, 
maybe it's a good idea to have a doc somewhere on how to use this package with docker with minimal sample. In case some other people need it.

Thanks for your time!

**Comment by julianhille** [comment]
oh i just saw you copy the app folder into the directory and then mount `./` into the container in app?

That just makes everything what happened on the build time completely irrelevant. 
you need to remove the app volume mount too `./:/app`

**Comment by julianhille** [comment]
[muhammara-docker.zip](https://github.com/julianhille/MuhammaraJS/files/10215960/muhammara-docker.zip)
there you go minimal example

**Comment by hilmanski** [comment]
Thanks for providing the minimal sample. 
Here's the error result when I try run the docker

https://app.warp.dev/block/iASy7kxYLh2MCFHXfrtzQo

**Comment by julianhille** [comment]
Thank you I think I learned something. Are you using an m1 or similar hardware which architecture is arm64 or armv8?

**Comment by hilmanski** [comment]
Yes, correct I'm running it on m1

**Comment by julianhille** [comment]
Then I suggest not to use alpine or readd the lines about compiling. Should I create an arm64 musl example?

**Comment by hilmanski** [comment]
Thanks for the hint. don't worry, will explore it and learn more about it first
Thanks for your time!

Re: "readd the lines about compiling"
can you point out what are you refering to here?

**Comment by julianhille** [comment]
> Re: "readd the lines about compiling" can you point out what are you refering to here?

i meant you need to readd this line into the sample Dockerfile and you should be good to go.

 ```RUN apk add g++ make py3-pip```

**Comment by julianhille** [comment]
Specifically for your case I added new pre builts for the next version. Would it be possible to try a specific beta version in your alpine docker container? I'm unable to test as I do not have any armv8 machine.
