### ISSUE TITLE
AWS lambda Prebuilds

### ISSUE THREAD

**Issue by Amaanuddin** [julianhille/MuhammaraJS#256]
Hi @julianhille, Can you provide steps to add Muhammara to AWS lambda function, also where can I find the latest prebuilds for AWS lambda?

**Comment by julianhille** [comment]
The steps are just install it.
Lambda is normally nothing special its just linux BUT you should make sure not to use any arm7 arm64 but x86 architecture. 

You also need to make sure to build you package on a similar hardware / libc and architecture.

for example:
You can not locally install on a mac package all into a zip and upload it to aws as the compiled binary would not fit the architecture needed for aws.

**Comment by julianhille** [comment]
There are no special builds for aws lambda they are just the usual linux x86 or arm64 musl builds depending on what you choose.

**Comment by julianhille** [comment]
Let me know if you need any further help.
You could also read from down [here](https://github.com/julianhille/MuhammaraJS/issues/155#issuecomment-1163415904).

I'd close this for now as i hopefully have provided enough info to solve your puzzle, but feel free to reopen if needed.

**Comment by Amaanuddin** [comment]
I was able to resolve the issue by following these steps
`
npm install

curl -L "https://github.com/julianhille/MuhammaraJS/releases/download/3.5.0/node-v83-linux-x64-glibc.tar.gz" | tar -xz

cp -f ./binding/muhammara.node ./node_modules/muhammara/binding/muhammara.node 

rm -r ./binding
`

My node version is 14.x, the development OS is Windows and Prod is AWS Lambda with Nodejs 14.x runtime

with this simple script, I'm replacing the Windows binding with Linux binding

**Comment by julianhille** [comment]
there are better more resilient ways to do that.
My  recommendation would be to build your system in a docker container or in your ci where the platform building fits the platform executing your app.

There are (at least) two more ways:
- set some npm_config env vars example to be seen here: https://github.com/julianhille/MuhammaraJS/blob/develop/.github/workflows/build.yml#L74 before installing.
- or call this `npx node-pre-gyp install --update-binary --target-platform=linux` (read more about it here: https://github.com/julianhille/MuhammaraJS/issues/155#issuecomment-1163439263)
 
The curl variant solves your problem but in a way which might break in the future.
