### ISSUE TITLE
Switch dependency from xmldom to @xmldom/xmldom 

### ISSUE THREAD

**Issue by rossgp** [julianhille/MuhammaraJS#262]
The recently published version 3.6.0 introduced a dependency on xmldom (v0.6.0). This package however was migrated from v0.7.0 to be published under @xmldom/xmldom 
the reasons this had to be done explained here: https://github.com/xmldom/xmldom/issues/271

xmldom has several security vulnerabilities that are only fixed in version published under @xmldom/xmldom so ideally the dependency would be switched to @xmldom/xmldom

**Comment by julianhille** [comment]
Thanks. Will do together with electron 23 rls. Would this work for you?

**Comment by rossgp** [comment]
Makes sense. Thanks!

**Comment by leantorres73** [comment]
This is exactly what I was looking for! 👏  .. we have npm security checks to deploy our services and I was moving away from phantomJS and trying to implement this library and it is a blocker for me. Awesome you have this in your roadmap, 
@julianhille  any estimated release date?

Thanks!

**Comment by julianhille** [comment]
If you send a PR I can release a 3.6.1 by tomorrow

**Comment by julianhille** [comment]
I'm just confused that GitHub security does not inform me here. Or did o overlook it?

**Comment by leantorres73** [comment]
![image](https://user-images.githubusercontent.com/12806363/215555183-b3eb4ffa-0667-4e8c-b7d6-0c5c0033e7f5.png)


Not sure why Github is not informing the issue, I agree..

**Comment by julianhille** [comment]
Not as easy as i thought, because the added muhammara / hummus recipe depends on an old xmldom.
The old version allows multiple nodes on root whereas the newer version only allows a single root node.
That's why i waste a bit of cpu cycles and map it into root node and extract it back from there.

**Comment by julianhille** [comment]
I just had another look at the security warnings and i must have overlooked it, i got a warning a week ago which i was totally unaware of. Once again, thanks for reporting.

**Comment by rossgp** [comment]
> Not as easy as i thought, because the added muhammara / hummus recipe depends on an old xmldom. The old version allows multiple nodes on root whereas the newer version only allows a single root node. That's why i waste a bit of cpu cycles and map it into root node and extract it back from there.

Thanks so much for look into the update. I would have struggled to find that problem myself as I've never used the muhammara / hummus recipe component before

**Comment by julianhille** [comment]
the recipe component is new, as the libs did not update / evolve anymore. So i decided to integrate it.

**Comment by julianhille** [comment]
Still has a pending run, but overall all action steps worked.
There is another issue #263 which id like to fix with a 3.6.1 as this currently prevents m1 users from using muhammara.

So, in the end this means it will take another day, because all the actions take a serious amount of time to finish.

**Comment by julianhille** [comment]
3.7.0 will be released today. sorry for the delay but every issue introduced a new one while fixing the other.

**Comment by julianhille** [comment]
thank you for your patience. there was another issue which needed to be resolved, which it is now, somehow.
Currently the builds are running and it should be released in about 4 hours.
