### ISSUE TITLE
Muhammara version 3.6.0 doesn't run on Mac M1

### ISSUE THREAD

**Issue by aismaelcap** [julianhille/MuhammaraJS#263]
Hi,I'm trying to run muhammaraJs on my machine.

Spec:
```bash
Chip Apple M1 Max
MacOS ventura 13.2
node version v14.18.0
npm version 6.14.15
```

As repro I'm using the following:

https://github.com/hilmanski/test-muhammara-arm64-musl

In the package.json, I replaced  "muhammara": "3.6.0-beta.1" with "muhammara": "3.6.0" in the dependencies

It installed successfully, but when I ran, I got the following error:

```bash
internal/modules/cjs/loader.js:1144
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/aismael/Documents/test-mh/node_modules/muhammara/binding/muhammara.node, 0x0001): tried: '/Users/aismael/Documents/test-mh/node_modules/muhammara/binding/muhammara.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/aismael/Documents/test-mh/node_modules/muhammara/binding/muhammara.node' (no such file), '/Users/aismael/Documents/test-mh/node_modules/muhammara/binding/muhammara.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/aismael/Documents/test-mh/node_modules/muhammara/lib/muhammara.js:6:35)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

Can you please help me with this?

**Comment by aismaelcap** [comment]
I tried with node version 18 and it ran successfully, however my project is using node version 14 and we cannot change the node version so rapidly.

**Comment by julianhille** [comment]
Can you please rm node modules dir, Install through npm or yarn install and attach the binary here?

I'd like to see what your system is downloading.

**Comment by aismaelcap** [comment]
this is the output when I clear node modules and package-lock, and reinstall:

```bash
% npm i  
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

> muhammara@3.6.0 install /Users/aismael/Documents/test-mh/node_modules/muhammara
> node-pre-gyp install --fallback-to-build ${EXTRA_NODE_PRE_GYP_FLAGS:-""}

[muhammara] Success: "/Users/aismael/Documents/test-mh/node_modules/muhammara/binding/muhammara.node" is installed via remote

> es5-ext@0.10.62 postinstall /Users/aismael/Documents/test-mh/node_modules/es5-ext
>  node -e "try{require('./_postinstall')}catch(e){}" || exit 0

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN muhammara-docker@1.0.0 No description
npm WARN muhammara-docker@1.0.0 No repository field.

added 135 packages from 99 contributors and audited 135 packages in 3.733s

5 packages are looking for funding
  run `npm fund` for details

found 2 vulnerabilities (1 moderate, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by aismaelcap** [comment]
do you need the package-lock output (as a result of the install)  as well?

**Comment by julianhille** [comment]
I'd like this file:
users/aismael/Documents/test-mh/node_modules/muhammara/binding/muhammara.node attached please

**Comment by aismaelcap** [comment]
[muhammara.txt](https://github.com/julianhille/MuhammaraJS/files/10538365/muhammara.txt)
had to rename the extension to txt for it to accept the file format

**Comment by julianhille** [comment]
you are right. Something is wrong. The file is not arm but instead is x64.

**Comment by julianhille** [comment]
i somehow fucked that up, will try to fix that shortly. Sorry for any inconvenience.

**Comment by daniele-zurico** [comment]
feel free to create a temporary version with whatever name you prefer and we'll test it locally. Thanks for your support

**Comment by julianhille** [comment]
An action is running and should produce a valid arch. Will let you know how and when to test

**Comment by julianhille** [comment]
I'd love to have good news, but somehow github actions is having some difficulties.
The musl node 11.2.0 machine will not run and has issues checking out the code. As long as this is not running we're unable to retrieve the binary files.

**Comment by julianhille** [comment]
Ok. I thought this is a temporary issue but it seems something in the docker build or checkout action itself changed. Even old runs (from 3 weeks ago) fail when rebuilding.

**Comment by julianhille** [comment]
fixes are trying to build, will let you know if it works.

**Comment by julianhille** [comment]
Here are the bindings: https://github.com/julianhille/MuhammaraJS/suites/10764125187/artifacts/541059020 you could download all the binaries there and then choose the one you need. Mac os arm and the specific abi. If you don't know which one let me know the exact electron or node version. The containing .node file needs to be put into the binding dir after install and then test your scripts.

Let me know if it works or if you need further instructions.

**Comment by julianhille** [comment]
At least the arch of the binary is now correct so it should work.

**Comment by julianhille** [comment]
im sorry, but i did not hear anything back from you so i merged and released. that mach-o error should be solved.
the compiled native modules arch was x64 before and is now arm64. i checked as far as i can.

let me know if you have still issues. 3.7.0 release actions are running.

**Comment by aismaelcap** [comment]
So, I tried the bindings for my machine setup node-v83-darwin-arm64-unknown (node 14), it errored out.
tried node-v108-darwin-arm64-unknown and it worked for node 18. 

Also, apologies for the slow response and many thanks for your efforts thus far.

**Comment by julianhille** [comment]
ok yes i see it is still x64. this is odd.

**Comment by julianhille** [comment]
My bad I'm sorry. https://github.com/julianhille/MuhammaraJS/suites/10828234499/artifacts/546098018 please try these again 

https://github.com/julianhille/MuhammaraJS/pull/272 pr belonging to the issue

**Comment by julianhille** [comment]
ok well. ive some good news and some bad news.
the good news first: i've found the issue
the bad news: i can not help here. There just is no darwin arm64 (M1) nodejs for node version 14 and below. arm64 officially started with node v16.x

You can read about it here: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V16.md

v15 also works for darwin m1 (arm64) because it had some experimental support: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V15.md

unfortunately i've no idea how to help from here.

What i will do: remove darwin arm64 pre builts for abi 83 (v14) and below.

**Comment by daniele-zurico** [comment]
Hey @julianhille I suppose then you can create 3.70 then? At least we can have node 18 and arm64

**Comment by julianhille** [comment]
Node 15 and above should should work.

**Comment by daniele-zurico** [comment]
I meant that here https://www.npmjs.com/package/muhammara I can still see 3.6.0

**Comment by julianhille** [comment]
ah ok. yeah yes it is currently building will take 4 hours and then should be released.
