### ISSUE TITLE
Types Definition not included in the package

### ISSUE THREAD

**Issue by JustinDao** [julianhille/MuhammaraJS#276]
The types file is not included in the package [muhammara.d.ts](https://github.com/julianhille/MuhammaraJS/blob/develop/muhammara.d.ts)

I think we just need to add it here in the package.json: 

https://github.com/julianhille/MuhammaraJS/blob/develop/package.json#L32-L37

**Comment by julianhille** [comment]
You are absolutely right. Would you mind creating a pull request including the change and a changelog update? Would be great.

**Comment by JustinDao** [comment]
@julianhille done! https://github.com/julianhille/MuhammaraJS/pull/277

**Comment by JustinDao** [comment]
Thank you @julianhille ! Do you know when the next package release be put out with this update?

**Comment by julianhille** [comment]
Let me see this evening or tomorrow if there are some electron updates then I will add them and release shortly. Just a matter of days. Maybe Wednesday. Happy with that?

**Comment by JustinDao** [comment]
Perfect! :)
