### ISSUE TITLE
EncryptOptions in muhammara.d.ts is wrong

### ISSUE THREAD

**Issue by GuoliangWang** [julianhille/MuhammaraJS#285]
interface EncryptOptions {
      password?: string;
      ownerPassword?: string;
      userProtectionFlag?: number;
    }

   should be:

   interface EncryptOptions {
      password?: string;
      ownerPassword?: string;
      userPassword?: `string;`
      userProtectionFlag?: number;
    }

**Comment by julianhille** [comment]
thank you very much.  would you mind adding a PR or should i?
