### ISSUE TITLE
Generate thumbnail of pdfs

### ISSUE THREAD

**Issue by natnaeltibebu** [julianhille/MuhammaraJS#296]
I want to generate the thumbnail of pdfs how can i implement that with muhammaraJS.Thanks in advance.

**Comment by julianhille** [comment]
I'm sorry but muhammara can edit pdfs but is unable to generate thumbnails of it.
Here is a outline and module which should be able to do what you need: https://github.com/julianhille/MuhammaraJS/issues/187#issuecomment-1168885376


you may use:
https://www.npmjs.com/package/pdf2pic or https://www.npmjs.com/package/pdf-image


i close this for now but feel free to reopen if i did not understand correctly.

Have a good one.
