### ISSUE TITLE
Unable to start parsing PDF file error for PDFs

### ISSUE THREAD

**Issue by leantorres73** [julianhille/MuhammaraJS#309]
Hi,
I've been using this library and it's working great, but I'm getting an error on specific PDFs `TypeError: unable to append page, make sure it's fine` , which I'm able to open correctly. I'm guessing it does not like something from the header, although I'm not sure about it.

I saw this same ticket was opened last year and some fixes were made in release `3.2.0` to make it work but I'm wondering if we could improve/extend the functionality (https://github.com/julianhille/MuhammaraJS/issues/211).

**Comment by julianhille** [comment]
Are you able to provide a broken version of that pdf file or a similar broken file to reproduce the issue.

**Comment by leantorres73** [comment]
Hi Julian, I will try to give you one, as it has some personal/protected information I cannot share it directly.

**Comment by julianhille** [comment]
did you find a file ?

**Comment by julianhille** [comment]
without a sample file there is nothing i can do feel free to reopen if you got sime examples. thanks

**Comment by coolhand79** [comment]
We're still seeing this issue. Attached is a sample PDF that fails when attempting to merge.
[blank-bad.pdf](https://github.com/user-attachments/files/15811639/blank-bad.pdf)

Our merge code looks like this: 

```
export async function merge(
    inputPath: string,
    coversheetPath: string,
    outputPath: string
): Promise<void> {

    const outStream = new memoryStreams.WritableStream();

    const coversheetPDFBuffer = fs.readFileSync(coversheetPath);
    const reportPDFBuffer = fs.readFileSync(inputPath);

    try {
        const firstPDFStream = new muhammara.PDFRStreamForBuffer(coversheetPDFBuffer);
        const secondPDFStream = new muhammara.PDFRStreamForBuffer(reportPDFBuffer);

        const pdfWriter = muhammara.createWriterToModify(
            firstPDFStream,
            new muhammara.PDFStreamForResponse(outStream)
        );
        pdfWriter.appendPDFPagesFromPDF(secondPDFStream);
        pdfWriter.end();
        const newBuffer = outStream.toBuffer();
        outStream.end();

        fs.writeFileSync(outputPath, newBuffer);
    } catch (e: any) {
        outStream.end();
        throw new Error('Error during PDF combination: ' + e.message);
    }
}
```

When attempting to merge with this file 
[blank_coversheet.pdf](https://github.com/user-attachments/files/15811654/blank_coversheet.pdf)
the error returned will be `unable to append page, make sure it's fine`
