### ISSUE TITLE
how to use default fonts

### ISSUE THREAD

**Issue by manjilkhambe** [julianhille/MuhammaraJS#321]
I am trying to add watermark to the pdf file. I don't want to provide any font path. Is there a way to do it?
Please refer code below

<img width="666" alt="image" src="https://github.com/julianhille/MuhammaraJS/assets/17910112/e7a8ee8c-b08f-47e8-8909-264373012cb3">

**Comment by julianhille** [comment]
by default fonts you mean your system fonts right?

**Comment by julianhille** [comment]
if yes you might use os-fonts or get-system-fonts or some other similar fonts.

But be aware that this might not work ec2 or lambda instances if you do not have any access rights to some ttf or other font files or system / library folders.

Best way is to package some default fonts with your app and retrieve path from env config so anyone using your app could just add a path and change font path without editing the code.

**Comment by manjilkhambe** [comment]
No no, I wanted to use fonts used in library itself. I don't want to give the file path to getFontForFile function. Is there a way to achieve it  ?

**Comment by julianhille** [comment]
i'm not sure what this exactly means. do you have a font in memory like a buffer?

**Comment by manjilkhambe** [comment]
Using reciepe approach I can directly use font: 'Roboto'. similarly  is there a way so that I can directly provide font name - Robot | Helvetica etc fonts which are already there in the fonts folder of npm package. 

please refer below code which is written in unit tests in  
TestMaterials/ Reciepe/ text.js

<img width="960" alt="image" src="https://github.com/julianhille/MuhammaraJS/assets/17910112/0b96f2d3-222d-4ec5-8f61-4149d6a499a5">

**Comment by julianhille** [comment]
Ahhh got it. There is currently no other option besides using receipt which loads the default fonts.

**Comment by manjilkhambe** [comment]
okay. thanks for the reply.

**Comment by julianhille** [comment]
i could add a convinience function which adds a map of name -> pathes. that would make it easier. would that help?

**Comment by manjilkhambe** [comment]
yes. that would help I guess. Any sort of reference to the paths would do. It would be helpful in cases where user don't want to use custom fonts.
