### ISSUE TITLE
Event loop blocked when using muhammara to combine pdfs

### ISSUE THREAD

**Issue by efraimrodrigues** [julianhille/MuhammaraJS#332]
First of all, thank you for this great package. It's very handy and it's helping me and my team a lot.

I've the following function to combine pdfs using muhammara and memory-streams.
```
const combinePDFPages = pages => {
  const bufferedPages = pages.map(page => new muhammara.PDFRStreamForBuffer(page));
  let outStream = new memoryStreams.WritableStream();
  try {
    let pdfWriter = muhammara.createWriter(
      new muhammara.PDFStreamForResponse(outStream)
    );
    bufferedPages.forEach(page => pdfWriter.appendPDFPagesFromPDF(page));

    pdfWriter.end();
    let newBuffer = outStream.toBuffer();
    outStream.end();
    return newBuffer;
  } catch (error) {
    outStream.end();
    throw new Error("Error during PDF combination");
  }
};
```

 It does what it's supposed to do just fine, but it's blocking the event loop when we're combining pdfs with lots of pages. I'm not very familiarized with streams but I know it can help prevent blocking the event loop. Does any one have any insight on how I can refactor this code so that the event loop doesn't get blocked?

**Comment by julianhille** [comment]
This might help, did not really try. You could also try `process.nextTick()` instead of setImmediate. Let me know if that works.


```
for (page of bufferedPages) {  
    promise = new Promise((resolve) => {
      setImmediate(() => {
        pdfWriter.appendPDFPagesFromPDF(page);
        resolve()
      })
    })
    await promise
}
```

**Comment by julianhille** [comment]
Btw. all you do is writing sync code `.map`, `.forEach` everything is sync. This is not possible to not block the event loop like that.
Thats like a `for i in 1...1000000` with just printing the number and expect it not to block :>

**Comment by efraimrodrigues** [comment]
Thanks for the advice. I was expecting something more on the stream level itself like a pipe function, but I tried what you suggested and it did improve performance a little bit. 

Thank you @julianhille !

**Comment by julianhille** [comment]
will close for now, feel free to reopen if something changes.
