### ISSUE TITLE
GLIBC_2.29

### ISSUE THREAD

**Issue by IndyVC** [julianhille/MuhammaraJS#347]
Building a docker image fails with the following error: 
`ERROR: Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /__w/labeling-tool-gql/labeling-tool-gql/node_modules/muhammara/binding/muhammara.node)`

Dockerimage = node:18.18.2-buster

**Comment by julianhille** [comment]
please downgrade to muhammara < 4 and retest

**Comment by julianhille** [comment]
Here is a bit of explanation:

https://github.com/julianhille/MuhammaraJS/issues/333#issuecomment-1755713141

and the following comment may also help you:

https://github.com/julianhille/MuhammaraJS/issues/333#issuecomment-1759270414
