### ISSUE TITLE
Encrypt is not working and recrypt cleans pdf metadata

### ISSUE THREAD

**Issue by luicfrr** [julianhille/MuhammaraJS#350]
I'm trying to encrypt a pdf file but the following code is not working:
```
const pdfBuffer = Buffer.from( 'base64string', 'base64')
const encryptedBuffer = await new Promise<Buffer>(( res ) => {
    const recipe = new Recipe( pdfBuffer, undefined, {
        title: 'test title',
        author: 'test author',
        subject: 'test subject'
    } )
    recipe.encrypt( {
        userPassword: '123abc',
        ownerPassword: 'abc123',
        userProtectionFlag: 4
    } ).endPDF( buffer => res(buffer) )
} )
return res.send( encryptedBuffer )
```
If I save/open returned pdf on Adobe reader I can see all metada (title, author, subject, etc...) but no password is required to open the pdf and on file properties Adobe says the pdf is not password protected.

Then I tryed to move to `recrypt`, this is working and my pdf is now password protected but the problem is all metadata are cleared. All fields (title, subject, author, etc..) are empty. I've tryed recrypt using `encryptedBuffer`, also tryed adding metadata with other library and every metadata is present if I don't recrypt the pdf.

Here's my `recrypt` code:
```
const pdfBuffer = Buffer.from( 'base64string', 'base64')
const encryptedBuffer = await new Promise<Buffer>(( res ) => {
    const recipe = new Recipe( pdfBuffer, undefined, {
        title: 'test title',
        author: 'test author',
        subject: 'test subject'
    } )
    recipe.endPDF( buffer => {
          const readed = new PDFRStreamForBuffer( buffer )
          const encrypted = new PDFWStreamForBuffer()
          recrypt( readed, encrypted, {
              userPassword: '123abc',
              ownerPassword: 'abc123',
              userProtectionFlag: 4
          } )
          res( encrypted.buffer )
    } )
} )
return res.send( encryptedBuffer )
```

How can I have both

**Comment by julianhille** [comment]
That should not happen, encrypting should not remove metadata.

Have you tried in the first code to remove the protectionFlag and see what happens on default? 4 means allow printing if i remember right?

**Comment by luicfrr** [comment]
Yes, I've tryed removing `protectionFlag` but doesn't work. 

I've created this [codesanbox](https://codesandbox.io/p/sandbox/laughing-fire-xgj58r?file=%2Findex.ts%3A1%2C1) returning pdf's metadata logs. I'm using `pdf-lib` to add and read metadata from pdfs and as you can see on console logs, all metadata are cleared after encryption.

I also noticed that `endPDF` callback event is returning `undefined`(you'll see that `encryptedBuffer` variable is `undefined` and it's section is not even called) after encrypting pdf. Maybe this is another issue too.

EDIT:
Another test I've made is removing everything from `recrypt` with only read/write streams and, like before, all metadata are cleared:
```
// tryed running this code
recrypt( pdfRStream, pdfWStream )
```

**Comment by julianhille** [comment]
Currently my laptop is broken and so I'm unable tohelp or investigate.

**Comment by smart-handler127** [comment]
when will it be fixed sir?

**Comment by luicfrr** [comment]
@negaxsender I'm now using [this](https://github.com/Sparticuz/node-qpdf2) package instead.

In my case I needed to use a custom `qpdf` binary so I opened [this](https://github.com/Sparticuz/node-qpdf2/pull/39) pull request. 

Hope this helps you.

**Comment by polesapart** [comment]
I can confirm it strips the original metadata.

**Comment by xuakson** [comment]
i use PyPDF2 library python for the backend to create the rest api gateway then use it in my node js application, everything is fine and working perfectly, using only buffer so nothing saves on the disk. Only issue is that i get errors or fails when the request is too high

**Comment by julianhille** [comment]
Added a test receipt really throws stuff away. Will get to it.

**Comment by julianhille** [comment]
Getting to it again:
1. encryption a file in buffer mode is not supported. Your code:

```
const pdfBuffer = Buffer.from( 'base64string', 'base64')
const encryptedBuffer = await new Promise<Buffer>(( res ) => {
    const recipe = new Recipe( pdfBuffer, undefined, {
        title: 'test title',
        author: 'test author',
        subject: 'test subject'
    } )
    recipe.encrypt( {
        userPassword: '123abc',
        ownerPassword: 'abc123',
        userProtectionFlag: 4
    } ).endPDF( buffer => res(buffer) )
} )
return res.send( encryptedBuffer )

```

lacks handling errors and so hides that buffer encryption is not supported in recipe. will create a ticket.

https://github.com/julianhille/MuhammaraJS/issues/446

**Comment by julianhille** [comment]
can anyone confirm in the newest version that meta data got stripped? i can not any more.

File from test data
[Original.pdf](https://github.com/user-attachments/files/18202824/Original.pdf)

File after recrypt test ran:
[RecryptPDFOriginalToPasswordProtected.PDF](https://github.com/user-attachments/files/18202820/RecryptPDFOriginalToPasswordProtected.PDF)


Comparing meta:
![image](https://github.com/user-attachments/assets/b5ec440e-de04-485c-a949-c65776a9cb08)

For now i would close this. Feel free to reopen if this still persists or i do miss anything. Please don't take this serious or as an attack i'm just cleaning tickets and i can not confirm anymore.
