### ISSUE TITLE
No problem with installation, error when running, please help me see what I need to do。

### ISSUE THREAD

**Issue by Tithy** [julianhille/MuhammaraJS#353]
![image](https://github.com/julianhille/MuhammaraJS/assets/28753993/f665d990-4ad8-4bd0-b99a-310425169599)
![image](https://github.com/julianhille/MuhammaraJS/assets/28753993/1e664231-af23-4851-a7bb-ec16a907110f)
Electron version 19.1.19, nodejs version 16.14.2, win11。

**Comment by julianhille** [comment]
This looks like you are trying to use muhammara in the frontend (so in a browser).
By loading it through a js tag, a require inside of an electron window should work, depending on your setup, electron version and type of loading the file.
Loading it through some kind of require js by download and evaluate or js tags thhis wont work as there is no node which would be able to load a binary / native module.

**Comment by Tithy** [comment]
Thank you for your suggestion. I have rebuilt the entire project and it is now functioning properly. It is possible that some library versions were too low, and it seems that the canvas library is not compatible with my project.
