### ISSUE TITLE
Muhammara installation breaks "ERR code 7 command failed"

### ISSUE THREAD

**Issue by Eldo** [julianhille/MuhammaraJS#371]
Urgent help needed! A critical error with Muhammara has stalled progress since Thursday, jeopardizing my month-end deadline. While functional as "humus-recipe" locally/on servers, it's now failing in both environments. System information and error details are listed below. Your input in resolving this critical issue is greatly appreciated.
Operating System: Ubuntu 22.04.3 LTS              
Kernel: Linux 6.5.0-14-generic
Architecture: x86-64
ldd (Ubuntu GLIBC 2.35-0ubuntu3.6) 2.35

npm ERR! code 7
npm ERR! path /home/david/Documents/codes/pp/node_modules/muhammara
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build ${EXTRA_NODE_PRE_GYP_FLAGS:-""}

**Comment by Eldo** [comment]
I had to use hummus-recipe itself, version 2.0.1

**Comment by julianhille** [comment]
Please provide more error log as i like to solve this issue, even if its too late for you now.
