### ISSUE TITLE
muhammara.node was compiled against a different Node.js version using

### ISSUE THREAD

**Issue by izdaezt** [julianhille/MuhammaraJS#374]
I am currently using Node.js version 20 and Electron version 29.
When I declare a Recipe using the command: const Recipe = require("muhammara").Recipe;
then I encounter the following error:
**_muhammara.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 121._**

Please help me

**Comment by depperm** [comment]
I also experienced this, with different NODE_MODULE_VERSION (57, 93). I'll have to check but I believe this only happened to docker build, I think this worked while running locally.

This happened to me when upgrading node 9(something) to 16.15.0. We initially had hummus and thought switching to muhammara would fix it. 

Maybe relevant info:
node 16.15.0
npm 8.5.5
gcc 8.3.1

What I've tried to fix:
```
rm -rf node_modules
rm package-lock.json
npm cache clean -force
npm i
npm rebuild muhammara --update-binary
```
Nothing I've tried has worked

**Comment by nitzan-blink** [comment]
this has worked for me:
```
npm remove muhammara
npm install muhammara
```

**Comment by julianhille** [comment]
Make sure you install for your electron version and not for the node version or vice versa

**Comment by julianhille** [comment]
@depperm and for you, you need to make sure that you install "inside" of your docker container.
You can not install on the host and then move the node_modules into the container which may has a different node version.

Or a different os/arch Default libc etc

**Comment by julianhille** [comment]
> I am currently using Node.js version 20 and Electron version 29. When I declare a Recipe using the command: const Recipe = require("muhammara").Recipe; then I encounter the following error: **_muhammara.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 93. This version of Node.js requires NODE_MODULE_VERSION 121._**
> 
> Please help me

have a read: https://www.electronjs.org/docs/latest/tutorial/using-native-node-modules

**Comment by gilliamwells** [comment]
I too am experiencing issues with my local build on MacOS: 
The module '/node_modules/muhammara/binding/muhammara.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 115. This version of Node.js requires NODE_MODULE_VERSION 93. 

I tried everything mentioned above with no success.

Running Node 20.15.1
NPM 10.7.0

**Comment by julianhille** [comment]
> I too am experiencing issues with my local build on MacOS: The module '/node_modules/muhammara/binding/muhammara.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 115. This version of Node.js requires NODE_MODULE_VERSION 93.
> 
> I tried everything mentioned above with no success.
> 
> Running Node 20.15.1 NPM 10.7.0

please mind opening a new ticket. As the result and debugging is very very tightly coupled to your circumstances.

**Comment by julianhille** [comment]
is this still an issue?

**Comment by julianhille** [comment]
will close this for now as it is mostly a "install muhammara on machine 1 and then copy source over to machine 2" issue, ive not seen any cases then those
