### ISSUE TITLE
Mend.io has highlighed tar as a vulnerability on this package

### ISSUE THREAD

**Issue by mfernandes-alcumus** [julianhille/MuhammaraJS#408]
We have recently started using this package for our PDF updating and mend has highlighted tar, one of the packages a vulnerable. Please update this package as its raising some concerns in my organisation

**Comment by julianhille** [comment]
https://github.com/julianhille/MuhammaraJS/issues/393 and especially:
this comment: https://github.com/julianhille/MuhammaraJS/issues/393#issuecomment-2304358273
