### ISSUE TITLE
v5 not working with official node:20 Docker image

### ISSUE THREAD

**Issue by JakobMe** [julianhille/MuhammaraJS#422]
After updating to v5 we are no longer able to start our node backend inside a Docker container using the official `node:20` image:

```
node:internal/modules/cjs/loader:1586
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.31' not found (required by /app/node_modules/muhammara/binding/muhammara.node)
    at Module._extensions..node (node:internal/modules/cjs/loader:1586:18)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/app/node_modules/muhammara/lib/muhammara.js:6:35)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v20.17.0
```

The official `node:20` image is using Debian GNU/Linux 12 (bookworm); `libstdc++6` seems to be on the latest available version:

```
apt-get upgrade libstdc++6
libstdc++6 is already the newest version (12.2.0-14).
```

But the latest included `GLIBC` version is `GLIBCXX_3.4.30`.

**Comment by julianhille** [comment]
yes that is indeed an issue i can not really help with or currently see no viable version.
Github has removed ubuntu 18.04 as runner and so i had to use 20.04 which comes with the said glibc version.

**Comment by julianhille** [comment]
The only thing i can try is starting a debian container inside of the ubuntu runner.
But then i need to handle all the necessary required dependencies inside of it.

**Comment by julianhille** [comment]
link to issue: https://github.com/julianhille/MuhammaraJS/issues/423

**Comment by julianhille** [comment]
issue 423 is solved. now releasing

**Comment by bochkovyi** [comment]
I had the same issue, Ubuntu 22.04.2 LTS, v20.18.0, not using docker. 
 Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.31' not found (required by /data/orgbrain-db/node_modules/muhammara/binding/muhammara.node)
 
 strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX_3.4.31 gives nothing, while GLIBCXX_3.4.30 is available.
 
 HOW TO FIX:
 with some help of chat gpt, _not really understanding what I am doing_,
 sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install libstdc++6 g++-12

dpkg -s libstdc++6 | grep Version is not Version: 13.1.0-8ubuntu1~22.04
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX_3.4.31 now gives me the version
 
 So if somebody will come here to find the answers, leaving my solution here for everyone:)

**Comment by julianhille** [comment]
Did you Test with 5.0.2 without your fix?

**Comment by julianhille** [comment]
this does not seem to work. downgrade gcc works. now another PR. will release v5.1.0 with some new electron versions shortly. sorry any inconviences

**Comment by julianhille** [comment]
https://github.com/julianhille/MuhammaraJS/pull/431

**Comment by bochkovyi** [comment]
> Did you Test with 5.0.2 without your fix?

I was about to try it but I think i first made my fix, and only then updated the version:)

**Comment by julianhille** [comment]
Could you retry? Without ppa including? I'd guess it does not work

**Comment by bochkovyi** [comment]
> Could you retry? Without ppa including? I'd guess it does not work

Yes, tried on a different machine with ubuntu and version 5.0.2, same result, had to upgrade to gcc 13, then it works

**Comment by julianhille** [comment]
Downgrade has issues on some machines for electron. This is getting ugly from maintenance perspective.

**Comment by bochkovyi** [comment]
> Downgrade has issues on some machines for electron. This is getting ugly from maintenance perspective.

I guess since i found a solution how to upgrade - maybe just add it to readme and people will upgrade? Or is there any downside of upgrading?

**Comment by julianhille** [comment]
Ppas add extra steps and extra work. Muhammara should work with the default node docker build.

**Comment by julianhille** [comment]
Downgraded even further to gcC 11. This way it should Work.

**Comment by mrksdiehl** [comment]
I just had this issue today. Was using the latest version on Ubuntu 22 but still had the issue. Only with the ChatGPT solution above did I make it work.

**Comment by julianhille** [comment]
It's not released that's why this is still open

**Comment by JakobMe** [comment]
Upgrading to v5.1.0 fixes the issue, thank you! 🎉

**Comment by anawallgren** [comment]
I'm experiencing this same error on v5.3.0 using `node:20-bullseye`.

```
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /app/node_modules/.pnpm/muhammara@5.3.0/node_modules/muhammara/binding/muhammara.node)
   ...
  code: 'ERR_DLOPEN_FAILED'
}
Node.js v20.18.3
```

**Comment by julianhille** [comment]
you need to upgrade to bookworm. bullseye has gcc 10 but we need at least 11. bookworm has afaik version 12.
