### ISSUE TITLE
Error in AWS Lambda: invalid ELF header

### ISSUE THREAD

**Issue by lkowalski-smartbusiness** [julianhille/MuhammaraJS#43]
Following up here on an issue found when using HummusRecipe (https://github.com/chunyenHuang/hummusRecipe/issues/196)

Could you please make sure the package is built using these standards (most likely building as static libraries):
https://aws.amazon.com/blogs/compute/nodejs-packages-in-lambda/

I'm getting exactly the same issue as the guy who opened the issue in HummusRecipe

**Comment by julianhille** [comment]
I broke my laptop some days ago and it will take some time until a new one is there. I can not look at this until then.
There is also a electron 10 on windows issue which needs to be fixed before.

**Comment by julianhille** [comment]
Btw did you test `npm install muhammara --build-from-source` ?

Edit: 
or if you install through a package.json where muhammara is included you cold also try:
`npm install --build-from-source=myapp` this is documented here: https://www.npmjs.com/package/node-pre-gyp

**Comment by lkowalski-smartbusiness** [comment]
Hi @julianhille thanks for the hints! I'll certainly try and get back to you as soon as possible. For now I had to settle on running the `npm install` scripts for my function within a LambCI docker container

**Comment by julianhille** [comment]
btw got a new laptop and got some spare time in the next days, hopefully i can get to this.

**Comment by julianhille** [comment]
I'm not sure if static binding is a good idea as a pre built. This might needs including Infos about the bound lobs and their licenses. Needs thoroughly checking.
Maybe i can add functionality to set the binary path to be used then you could built it locally or in a ci, deploy it together with your code and set the binary path.

I guess it will still download the pre-built.

**Comment by julianhille** [comment]
Have you resolved your issue?

**Comment by julianhille** [comment]
Stale
