### ISSUE TITLE
Encrypt crashes with node docker alpine

### ISSUE THREAD

**Issue by hdiaz-nectia** [julianhille/MuhammaraJS#65]
Hi,

I am trying to encrypt an existing PDF running in a docker container but unexpectedly the container is exited when encrypt method is called. It is working on my local machine, however it crashes inside the node:12.19-alpine

```
import { recrypt } from 'muhammara';
...

console.log('before encrypt pdf');
recrypt(
    filenameSrc,
    filenameEnc,
    {
        password: key,
        userPassword: key,
        ownerPassword: key,
        userProtectionFlag: 4                   
    });
console.log('after encrypt pdf');
```

Dockerfile

```
# Build App
FROM node:12.19-alpine as builder

RUN mkdir /app/
WORKDIR /app

COPY . .

RUN yarn install
RUN yarn build

# Deploy App
FROM node:12.19-alpine as production

ENV PHANTOMJS_VERSION 2.1.1

RUN apk add --update --no-cache curl && \
    curl -Ls "https://github.com/dustinblackman/phantomized/releases/download/${PHANTOMJS_VERSION}/dockerized-phantomjs.tar.gz" | tar xz -C / && \ 
    curl -k -Ls https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-${PHANTOMJS_VERSION}-linux-x86_64.tar.bz2  | tar -jxvf - -C / && \
    cp phantomjs-${PHANTOMJS_VERSION}-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs && \
    rm -fR phantomjs-${PHANTOMJS_VERSION}-linux-x86_64 && \
    apk del curl

VOLUME /tmp

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

RUN mkdir -p /opt/app/
WORKDIR /opt/app

RUN adduser --disabled-password app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

RUN chown -R app:app /opt/app/dist
USER app

CMD ["node", "dist/main"]
```

Also I tried this solution https://github.com/chunyenHuang/hummusRecipe/issues/170 but doesn't works

```
RUN apk add  g++ gcc libgcc libstdc++ linux-headers make python
RUN npm install -g node-gyp 
RUN npm install
RUN npm rebuild hummus --build-from-source
```

**Comment by hdiaz-nectia** [comment]
My mistake, the correct is:

`RUN npm rebuild muhammara --build-from-source`

**Comment by julianhille** [comment]
So it fixes it if you rebuild but it does not work when using the pre-build right?

**Comment by hdiaz-nectia** [comment]
> So it fixes it if you rebuild but it does not work when using the pre-build right?

Exactly, but I don't know why... Is it posibly solved this issue without rebuild ?

**Comment by julianhille** [comment]
i'll have a look.

Reopen because it should not be needed to recompile on build.

**Comment by julianhille** [comment]
Not sure what you are seeing there but my local tests works just fine.

Heres my minimal setup:
[test.zip](https://github.com/julianhille/MuhammaraJS/files/5586278/test.zip)

**Comment by hdiaz-nectia** [comment]
> Not sure what you are seeing there but my local tests works just fine.
> 
> Heres my minimal setup:
> [test.zip](https://github.com/julianhille/MuhammaraJS/files/5586278/test.zip)


I downloaded your example but doesn't work and I did the following:

Docker build

```sh
hector@hector-PC:~/Downloads/docker-alpine-muhammara$ docker build . --tag test-pdf
Sending build context to Docker daemon  33.28kB
Step 1/7 : FROM node:12.19-alpine as builder
 ---> cd874400360a
Step 2/7 : RUN mkdir /app/
 ---> Running in d07f5c54a2e9
Removing intermediate container d07f5c54a2e9
 ---> bf6f3d9d85df
Step 3/7 : WORKDIR /app
 ---> Running in 86a130e291b6
Removing intermediate container 86a130e291b6
 ---> 46c5079fd990
Step 4/7 : COPY . /app
 ---> 2b684e37e8c9
Step 5/7 : RUN yarn install
 ---> Running in adedb5583440
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 5.78s.
Removing intermediate container adedb5583440
 ---> 9f8638f12a31
Step 6/7 : RUN ls
 ---> Running in d4bd613b4fd9
Dockerfile
index.js
node_modules
package.json
test.pdf
yarn.lock
Removing intermediate container d4bd613b4fd9
 ---> 8e0e26883b2f
Step 7/7 : CMD ["node", "index.js"]
 ---> Running in db6d0c4d1b02
Removing intermediate container db6d0c4d1b02
 ---> c403e93f04c4
Successfully built c403e93f04c4
Successfully tagged test-pdf:latest
```
Then I run docker container

```sh
hector@hector-PC:~/Downloads/docker-alpine-muhammara$ docker run --rm -p 3001:3000 test-pdf
before encrypt pdf
after encrypt pdf
```
And finally check for new pdf file

```sh
hector@hector-PC:~/Downloads/docker-alpine-muhammara$ ls -l
total 40
-rw-rw-r-- 1 hector hector   141 nov 24 10:25 Dockerfile
-rw-rw-r-- 1 hector hector   378 nov 24 10:11 index.js
-rw-rw-r-- 1 hector hector   155 nov 23 23:37 package.json
-rw------- 1 hector hector  7482 nov 23 23:58 test.pdf
-rw-rw-r-- 1 hector hector 20021 nov 23 23:37 yarn.lock

hector@hector-PC:~/Downloads/docker-alpine-muhammara$ docker run -it -p 3001:3000 --entrypoint=/bin/sh test-pdf
/app # ls -l
total 44
-rw-rw-r--    1 root     root           141 Nov 24 13:25 Dockerfile
-rw-rw-r--    1 root     root           378 Nov 24 13:11 index.js
drwxr-xr-x   70 root     root          4096 Nov 24 13:27 node_modules
-rw-rw-r--    1 root     root           155 Nov 24 02:37 package.json
-rw-------    1 root     root          7482 Nov 24 02:58 test.pdf
-rw-rw-r--    1 root     root         20021 Nov 24 02:37 yarn.lock
/app # 
```

When I test with visual studio code without docker the file is created but always password is incorrect.

**Comment by julianhille** [comment]
after joining the docker image you need to issue `node index.js`

it works perfectly fine with binding the dir and creating the encrypted pdf inside the mounted directory.
I also tested opening the encrypted pdf and my viewer asked me for the password and was then able to show the pdf.

I made the test even more minimal:

My Dockerfile now looks like:
```# Build App
FROM node:12.19-alpine as builder

CMD ["/bin/sh"]
```


What i did with the new Dockerfile:

build docker alpine: `docker build ./ -t alpine-pdf-test`
run alpine test: `docker run -a stdin -a stdout --mount type=bind,source="$(pwd)",target=/app -it alpine-pdf-test /bin/sh`

inside the docker container:

```
cd /app
yarn install
node index.js
```

Now have a look in your host system at the dir there is now an encrypted.pdf

**Comment by hdiaz-nectia** [comment]
Ok, I did the last and I can create pdf in my host, but still I can open with any pdf viewer (chrome, wps, ...) 

_password: abc_

![DeepinScreenshot_Seleccionar área_20201124110903](https://user-images.githubusercontent.com/27019660/100104907-8261ca00-2e45-11eb-8bbf-fa1d47a59119.png)

**Comment by julianhille** [comment]
The password is: `abc;` be careful there is a `;`

**Comment by hdiaz-nectia** [comment]
> The password is: `abc;` be careful there is a `;`

Thanks, finally your example it works! but still have the problem in my project using Nest JS, I'll try to find out what is the error

The main difference is that the original pdf was created using html-pdf package like a buffer and I write to system using

```js
const filenameSrc =  `/tmp/src_${Date.now()}.pdf`;
const filenameEnc =  `/tmp/des_${Date.now()}.pdf`;
fs.writeFileSync(filenameSrc, srcBuffer);  

recrypt(
    filenameSrc,
    filenameEnc,
    {
        password: key,
        userPassword: key,
        ownerPassword: key,
        userProtectionFlag: 4                   
    });        

const encryptedBuffer = fs.readFileSync(filenameEnc);

fs.unlinkSync(filenameSrc);
fs.unlinkSync(filenameEnc);
```

**Comment by hdiaz-nectia** [comment]
Finally, I figure out that the problem was that I was copying **node_modules** folder from my host to docker image

Dockerfile
`COPY . .`

So, I add **.dockerignore** file and it works

```
.git
docker-compose*.yml
Dockerfile
node_modules
```
Thanks for your help

**Comment by julianhille** [comment]
Glad you have figured it out. You're welcome.

**Comment by suyogbaldota-harbinger** [comment]
> Finally, I figure out that the problem was that I was copying **node_modules** folder from my host to docker image
> 
> Dockerfile
> `COPY . .`
> 
> So, I add **.dockerignore** file and it works
> 
> ```
> .git
> docker-compose*.yml
> Dockerfile
> node_modules
> ```
> 
> Thanks for your help

@julianhille Can you please elaborate your solution? What impacts if I keep copying **node_modules** folder from host to container? I also got this issue for one of my application running inside a container and also it was resolved by adding this **node_modules** folder inside .dockerignore file, but I didn't get the root cause. Is it related to file/folder permission issue?

**Comment by julianhille** [comment]
sorry didnt see this question before.
The issue is your host and the guest docker container may have different platforms.
For example windows / mac host and an alpine guest.
Muhammara has native, compiled, bindings. Every native module belongs to an architecture, platform and c library. That said you can not install on your windows host and copy all the modules over to linux and expect everything to work, at least not native modules.
