### ISSUE TITLE
Question: Will Stream be implemented for Recrypt Function?

### ISSUE THREAD

**Issue by PhakornKiong** [julianhille/MuhammaraJS#92]
I'm having a simple requirement to add encryption to an existing PDF (No other modification). 

As my client is sending over base64 String over, I'm hoping to use either `Buffer` or `Stream` to do encryption and send back the new base64 String.

I quickly went through the code and found out that `Recrypt` function from the underlying library doesn't support `Buffer`, so that's out of question.

But i saw from the following that `Recrypt` should support stream, but i got an error when run the code below.

`TypeError: Unable to recrypt files, check that input and output files are clear and arguments are coool`
```Javascript
const oriReadStream = fs.createReadStream(__dirname + '/input.pdf');
const outWriteStream = fs.createWriteStream(__dirname + '/out.pdf');
muhammara.recrypt(oriReadStream, outWriteStream, {
  userPassword: 'user1',
  ownerPassword: 'owner1',
  userProtectionFlag: 4,
});
```

Some digging and I found out that there is a comment at the bottom. Will this get implemented?
https://github.com/julianhille/MuhammaraJS/blob/d59ceb85034b134ac3745eb7acdbeb21b974da20/muhammara.d.ts#L41-L45

**Comment by julianhille** [comment]
If I get to it.Why not. Feel free to implement it.😂

**Comment by julianhille** [comment]
i did take a tiny look and:
```
var wStream = new muhammara.PDFWStreamForFile(__dirname + '/output/RecryptPDFWithPasswordToNewPassword.PDF')
var rStream = new muhammara.PDFRStreamForFile(__dirname + '/TestMaterials/PDFWithPassword.PDF')
muhammara.recrypt(
rStream,
wStream,
{
	password:'user',
	userPassword: 'user1',
	ownerPassword: 'owner1',
	userProtectionFlag: 4
});

```

and this seems to work.

**Comment by julianhille** [comment]
Sorry this is bs. Back to the drawing board.

**Comment by PhakornKiong** [comment]
You might want to take a look at how I give it a try at `pdf-lib`, especially on the `PDFWriter` part.

https://github.com/Hopding/pdf-lib/pull/917

Maybe if the underlying writer can be updated to follow this implementation? I'm not really familiar with C++, that's why i gave it a try at the other libraries =D

**Comment by rvigneshw** [comment]
For your use case, you can try this code, 
`
const inputStream = new muhammara.PDFRStreamForBuffer(
      Buffer.from(buffer)
);
const outputStream = new muhammara.PDFWStreamForBuffer();
muhammara.recrypt(
  inputStream,
  outputStream,
  passwordOptions
);
`

Or I've created an abstraction on top of this muhammaraJS, [bufferToBuffer](https://github.com/rvigneshw/pdfence#buffer-to-buffer)

Working example: [https://replit.com/@rvigneshw/PDFence-Demo#index.js](https://replit.com/@rvigneshw/PDFence-Demo#index.js)

**Comment by julianhille** [comment]
@rvigneshw do you mind me integrating that directly into muhammara?

**Comment by rvigneshw** [comment]
@julianhille Sure no problem 👍

**Comment by julianhille** [comment]
I added a test to show how this would work with a buffer.

**Comment by lancedolan** [comment]
[rvigneshw](https://github.com/rvigneshw)'s solution not working for me.

```
"muhammara": "^3.8.0"
```

```
  const existingPdfBytes = fs.readFileSync(INPUT_FILE_NAME)
  const inputStream = new muhammara.PDFRStreamForBuffer( existingPdfBytes );
  const outputStream = new muhammara.PDFWStreamForBuffer();
  muhammara.recrypt( inputStream, outputStream);
```

```
TypeError: Unable to recrypt files, check that input and output files are clear and arguments are coool
```

Any thoughts?

**Comment by julianhille** [comment]
you are missing the options for recrypt. like current password, new userpassword and ownerpassword
